# Import Library

In [1]:
import pickle
import numpy as np
import pandas as pd
from sklearn.externals import joblib
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, cross_validate

ImportError: ignored

In [3]:
import pickle
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, cross_validate

# Baca Dataset

In [2]:
data = pd.read_csv('indian_liver_patient.csv', sep=',')
data.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  label  
0      3.3                        0.90      1  
1      3.2                        0.74      1  
2      3.3                        0.89      1  
3      3.4                        1.00      1  
4      2.4                        0.40      1

# Pemisahan Data

In [4]:
# AMBIL LABEL SETIAP BARIS
label = data.iloc[:,-1:].values.ravel()
label

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2,

In [5]:
# AMBIL FEATURE DATA
feature = data.iloc[:,:-1]
feature.values

array([[65.        ,  0.        ,  0.7       , ...,  6.8       ,
         3.3       ,  0.9       ],
       [62.        ,  1.        , 10.9       , ...,  7.5       ,
         3.2       ,  0.74      ],
       [62.        ,  1.        ,  7.3       , ...,  7.        ,
         3.3       ,  0.89      ],
       ...,
       [15.        ,  1.        ,  0.69613658, ...,  7.21352197,
         4.10193171,  1.29613658],
       [42.        ,  1.        ,  1.98280259, ...,  7.74963256,
         3.98304755,  0.98329251],
       [39.        ,  1.        ,  1.40457703, ...,  6.59542297,
         3.24129361,  0.90825872]])

In [8]:
# PEMBAGIAN DATA LATIH DAN DATA UJI SEBANYAK 80% UNTUK DATA LATIH 20% UNTUK DATA TEST
X_train, X_test, y_train, y_test = train_test_split(feature, label ,test_size=0.2)

In [9]:
print("Jumlah Data Latih:", len(X_train))
print("Jumlah Data Uji:", len(X_test))

Jumlah Data Latih: 662
Jumlah Data Uji: 166


# Pemodelan Dengan KNN

In [10]:
# PEMODELAN MENGGUNAKAN KNN
clf = KNeighborsClassifier(n_neighbors=8)

# FITTING DATA TRAINING
clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

# Prediksi Hasil

In [11]:
pred = clf.predict(X_test)
pred

array([2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2,
       1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1,
       1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1,
       1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1,
       2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1])

In [12]:
cols = {
    'Y True' : y_test,
    'Predict' : pred,
}

print("Prediksi Yang Dihasilkan")
pd.DataFrame(cols)

Prediksi Yang Dihasilkan


Y True  Predict
0         2        2
1         1        2
2         1        1
3         2        2
4         1        1
..      ...      ...
161       1        2
162       2        2
163       2        2
164       1        1
165       1        1

[166 rows x 2 columns]

# Pengukuran Performance

In [13]:
# FOLD = 10
kfold = KFold(n_splits=10)
scores = ['accuracy', 'precision', 'recall']
results = cross_validate(clf, X_test, y_test, cv=kfold, scoring=scores, return_train_score=True)
results_data = pd.DataFrame(results)
results_data

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
0  0.008393    0.016253       0.705882        0.771812        0.750000   
1  0.002855    0.006480       0.764706        0.751678        0.800000   
2  0.002421    0.005589       0.823529        0.751678        0.777778   
3  0.002312    0.005563       0.647059        0.751678        0.625000   
4  0.002295    0.005800       0.647059        0.751678        0.714286   
5  0.002388    0.005686       0.470588        0.778523        0.500000   
6  0.002303    0.101202       0.687500        0.766667        0.636364   
7  0.002492    0.005639       0.687500        0.773333        0.600000   
8  0.002424    0.005644       0.812500        0.753333        0.875000   
9  0.002352    0.005607       0.875000        0.760000        0.800000   

   train_precision  test_recall  train_recall  
0         0.750000     0.666667      0.828947  
1         0.750000     0.800000      0.760000  
2         0.732558     0.875000      0.818182  
3         0.743902     0.625000      0.792208  
4         0.734940     0.555556      0.802632  
5         0.765432     0.444444      0.815789  
6         0.750000     0.875000      0.818182  
7         0.768293     0.857143      0.807692  
8         0.746835     0.777778      0.776316  
9         0.753086     1.000000      0.792208

In [14]:
print("PERFORMANCE MODEL KNN")

accuracy = results_data.test_accuracy.mean() * 100
precision = results_data.test_precision.mean() * 100
recall = results_data.test_recall.mean() * 100

print("Accuracy : %0.2f" % accuracy, "%")
print("Precision : %0.2f " % precision, "%")
print("Recall : %0.2f " % recall, "%")

PERFORMANCE MODEL KNN
Accuracy : 71.21 %
Precision : 70.78  %
Recall : 74.77  %


In [15]:
pickle.dump(clf, open('model_new.pkl','wb'))